Maintenance

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -5,62 +5,89 @@ permissions:
 
 on:
   push:
-    tags: [ 'v*.*.*' ]
+    tags: ["v*.*.*"]
 
   workflow_dispatch:
     inputs:
       releaseTag:
-        description: 'Existing git tag to be released (i.e. v1.0.0)'
+        description: Existing git tag (i.e. v0.1.0)
         required: true
+      dryRun:
+        description: Dryrun
+        default: "true"
+        type: choice
+        options:
+          - "true"
+          - "false"
 
 jobs:
+  check:
+    runs-on: ubuntu-latest
+    if: (github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref_type == 'tag'))
+    outputs:
+      RELEASE_TAG: ${{ steps.check-tag.outputs.RELEASE_TAG }}
+      REPO_NAME: ${{ steps.check-tag.outputs.REPO_NAME }}
+    steps:
+      - name: Check release tag
+        id: check-tag
+        uses: actions/github-script@v6
+        with:
+          script: |
+            console.log('github.event_name', '${{ github.event_name }}')
+            console.log('github.ref_type', '${{ github.ref_type }}')
+            let releaseTag
+            if('${{ github.event_name }}' == 'workflow_dispatch') {
+              releaseTag = '${{ github.event.inputs.releaseTag }}'
+            } else if('${{ github.event_name }}' == 'push' && '${{ github.ref_type }}' == 'tag') {
+              releaseTag = '${{ github.ref }}'.replace(/^refs\/tags\//, '');
+            } else {
+              console.log('no semver tag found')
+              return
+            }
+            console.log('RELEASE_TAG', releaseTag)
+            core.setOutput('RELEASE_TAG', releaseTag)
+            console.log('REPO_NAME', context.repo.repo)
+            core.setOutput('REPO_NAME', context.repo.repo)
+
+      - name: Check tag semver
+        id: check-tag-semver
+        uses: madhead/semver-utils@cd1ddc05fca0b1514b697c2ca9fe88d4df4000ae # latest as of 2022-11-11
+        if: ${{ steps.check-tag.outputs.RELEASE_TAG != '' }}
+        with:
+          version: ${{ steps.check-tag.outputs.RELEASE_TAG }}
+          lenient: false # fail on error
 
   test:
     runs-on: ubuntu-latest
+    needs: check
+    if: ${{ needs.check.outputs.RELEASE_TAG != '' }}
+    outputs:
+      RELEASE_TAG: ${{ needs.check.outputs.RELEASE_TAG }}
     steps:
       - name: Setup Go environment
-        uses: actions/setup-go@v2
+        uses: actions/setup-go@v3
         with:
-          go-version: '1.17'
+          go-version: "1.19"
 
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
+        if: ${{ needs.check.outputs.RELEASE_TAG != '' }}
         with:
-          # https://github.com/actions/checkout/issues/100
-          fetch-depth: 0
+          ref: ${{ needs.check.outputs.RELEASE_TAG }}
+          fetch-depth: 0 # Ref: https://github.com/actions/checkout/issues/100
 
-      - name: Install test tools
+      - name: Run tests
         run: |
-          make test-tools
-
-      - name: Run Tests
-        run: |
+          make init-tools
           make test
 
   release:
     runs-on: ubuntu-latest
     needs: test
-    outputs:
-      RELEASE_TAG: ${{ steps.env.outputs.RELEASE_TAG }}
+    if: ${{ needs.test.outputs.RELEASE_TAG != '' }}
     steps:
-      - name: Setup ENV
-        id: env
-        run: |
-          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
-            RELEASE_TAG=${{ github.event.inputs.releaseTag }}
-          elif [[ "${GITHUB_REF}" == refs/tags/v*.*.* ]]; then
-            RELEASE_TAG=${GITHUB_REF/refs\/tags\//}
-          fi
-          if [[ "${RELEASE_TAG}" != v*.*.* ]]; then
-            echo "invalid release tag (${RELEASE_TAG} - ${GITHUB_REF}), only semver is allowed (i.e v*.*.*)"
-            exit 1
-          fi
-          echo "::set-output name=RELEASE_TAG::${RELEASE_TAG}"
-
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Release
-        uses: softprops/action-gh-release@v0.1.14
+      - name: Make a release
+        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
+        if: github.event.inputs.dryRun != 'true'
         with:
-          tag_name: ${{ steps.env.outputs.RELEASE_TAG }}
+          tag_name: ${{ needs.test.outputs.RELEASE_TAG }}
